//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmeManager.Proxy.RaykingEmeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RaykingEmeService.IRaykingProxy")]
    public interface IRaykingProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRaykingProxy/DoProxy", ReplyAction="http://tempuri.org/IRaykingProxy/DoProxyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object DoProxy(string AssemblyName, string ClassName, string MethodName, object[] args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRaykingProxyChannel : EmeManager.Proxy.RaykingEmeService.IRaykingProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RaykingProxyClient : System.ServiceModel.ClientBase<EmeManager.Proxy.RaykingEmeService.IRaykingProxy>, EmeManager.Proxy.RaykingEmeService.IRaykingProxy {
        
        public RaykingProxyClient() {
        }
        
        public RaykingProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RaykingProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RaykingProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RaykingProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object DoProxy(string AssemblyName, string ClassName, string MethodName, object[] args) {
            return base.Channel.DoProxy(AssemblyName, ClassName, MethodName, args);
        }
    }
}
